version: "3.9"

services:
  app:
    build: .
    ports:
      - "3030:3030"
    environment:
      MCP_TRANSPORT: http
      MCP_TOKEN: change-me
      DATABASE_PROVIDER: postgresql
      DATABASE_URL: postgres://mcp:mcp@db:5432/mcp
      PORT: 3030
      NODE_ENV: production
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: mcp
      POSTGRES_PASSWORD: mcp
      POSTGRES_DB: mcp
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
